name: allapis
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_button: ^0.2.0
  http: ^0.13.3
  flip_card: ^0.5.0
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/bg.jpg
     - assets/images/1.png
     - assets/images/2.png
     - assets/images/3.png
     - assets/images/4.png
     - assets/images/5.png
     - assets/images/6.png
     - assets/images/7.png
     - assets/images/8.png
     - assets/images/9.png
     - assets/images/10.png
     - assets/images/11.png
     - assets/images/12.png
     - assets/images/13.png
     - assets/images/14.png
     - assets/images/15.png
     - assets/images/16.png
     - assets/images/17.png
     - assets/images/18.png
     - assets/images/19.png
     - assets/images/20.png
     - assets/images/21.png
     - assets/images/22.png
     - assets/images/23.png
     - assets/images/24.png
     - assets/images/25.png
     - assets/images/26.png
     - assets/images/27.png
     - assets/images/28.png
     - assets/images/29.png
     - assets/images/30.png
     - assets/images/31.png
     - assets/images/32.png
     - assets/images/33.png
     - assets/images/34.png
     - assets/images/35.png
     - assets/images/36.png
     - assets/images/37.png
     - assets/images/38.png
     - assets/images/39.png
     - assets/images/40.png
     - assets/images/41.png
     - assets/images/42.png
     - assets/images/43.png
     - assets/images/44.png
     - assets/images/45.png
     - assets/images/loading.gif
     - assets/images/cat.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Staatliches
       fonts:
         - asset: 'assets/fonts/Staatliches-Regular.ttf'
     - family: marker
       fonts:
         - asset: 'assets/fonts/PermanentMarker-Regular.ttf'


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
